repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-yaml
